services:
  pollution:
    build:
      context: .
      dockerfile: Dockerfile
    image: pollution:latest
    ports:
      - "31467:3000"
    environment:
      SESSION_SECRET: ${SESSION_SECRET:-session-secret}
      PASSWORD_MAC_KEY: ${PASSWORD_MAC_KEY:-mac_key}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      FLAG: "${FLAG:-grey{local_test_flag}}"
    mem_limit: 96m
    cpus: 0.2
    init: true
    cap_drop:
      - NET_RAW
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
