# Generated by Django 4.2.27 on 2026-01-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('picture', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default='20.00', max_digits=5)),
                ('description', models.TextField(default="It's a book... the pages are paper... and it's very booky.")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.author')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('author', 'Author'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteuser')),
                ('for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.book')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.siteuser'),
        ),
    ]
