# Generated by Django 4.2.27 on 2026-01-09 14:17

from django.db import migrations
import secrets
import string

alphabet = string.ascii_letters + string.digits

def seed(apps, schema_editor):
    author_model = apps.get_model('main', 'Author')
    book_model = apps.get_model('main', 'Book')
    siteuser_model = apps.get_model('main', 'SiteUser')
    review_model = apps.get_model('main', 'Review')

    admin_user, _ = siteuser_model.objects.get_or_create(username='Admin', password=''.join(secrets.choice(alphabet) for _ in range(32)), role='admin')
    random_user1, _ = siteuser_model.objects.get_or_create(username='Joe B.', password=''.join(secrets.choice(alphabet) for _ in range(32)), role='customer')
    random_user2, _ = siteuser_model.objects.get_or_create(username='Sebastian S.', password=''.join(secrets.choice(alphabet) for _ in range(32)), role='customer')

    aut, _ = author_model.objects.get_or_create(name='William S. Vincent', bio='')
    book, _ = book_model.objects.get_or_create(title='Django for beginners', author=aut, picture='0.jpg', price='31.99', description='Django for Beginners is a project-based introduction to Django, the popular Python-based web framework. Suitable for total beginners who have never built a website before and professional programmers looking for a fast-paced guide to modern web development and Django fundamentals.')
    review_model.objects.get_or_create(for_book=book, by_user=random_user1, text='Amazing, I can finally leave PHP behind.')

    aut, _ = author_model.objects.get_or_create(name='Steve Klabnik', bio='')
    book, _ = book_model.objects.get_or_create(title='The Rust Programming Language', author=aut, picture='1.jpg', price='42.99', description='With over 50,000 copies sold, The Rust Programming Language is the quintessential guide to programming in Rust. Thoroughly updated to Rust’s latest version, this edition is considered the language’s official documentation.')
    review_model.objects.get_or_create(for_book=book, by_user=admin_user, text='After reading this book, and finally understanding rust, I now feel an irresistible urge to rewrite everything I come across in rust.')

    aut, _ = author_model.objects.get_or_create(name='Dennis M. Ritchie', bio='')
    book, _ = book_model.objects.get_or_create(title='The C Programming Language', author=aut, picture='2.jpg', price='60.00', description="The authors present the complete guide to ANSI standard C language programming. Written by the developers of C, this new version helps readers keep up with the finalized ANSI standard for C while showing how to take advantage of C's rich set of operators, economy of expression, improved control flow, and data structures.")
    review_model.objects.get_or_create(for_book=book, by_user=random_user2, text='I now dream of C code - is that supposed to happen?')

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.RunPython(seed),
    ]
